################################
#			       #
#  Work Hour Monitor Makefile. #
#			       #
################################

# GCC compile flags

GNUCC = gcc

GNUCFLAGS = -ggdb -Wall -Wextra -Wpedantic -Wno-unused-parameter -Wno-unused-variable \
             -wno-format -std=c90

########################

CC = ${GNUCC}
CFLAGS = ${GNUCFLAGS}


OBJECTS =
HEADERS =

prog_name = whm
